### ISSUE TITLE
Framework Aborts

### ISSUE THREAD

**Issue by LulzRose** [epsylon/xsser#26]
Whenever I use the wizard on any site I receive: [Error] Crawlering system is not receiving feedback... aborting! :(

Please Help!

**Comment by epsylon** [comment]
@LulzRose I will take a look to it, soon.

**Comment by LulzRose** [comment]
Thank you @epsylon

**Comment by epsylon** [comment]
related -> https://github.com/epsylon/xsser/issues/27#issuecomment-380459116

**Comment by epsylon** [comment]
fixed: removed SSL deprecated method: https://github.com/epsylon/xsser/issues/27#issuecomment-380459116
