### ISSUE TITLE
Google not supported ?

### ISSUE THREAD

**Issue by syrius01** [epsylon/xsser#31]
Hi,

Is there any way I can make google search engine working with XSSer ?

 ./xsser -d 'search.php?q=' --De=google
===========================================================================

XSSer v1.7b: "ZiKA-47 Swarm!" - 2011/2018 - (GPLv3.0) -> by psy

===========================================================================
Testing [XSS from Dork-Query]... Good luck! ;-)
===========================================================================

[Error] This search engine is not supported!

[Info] List of available:
-------------------------
+ bing
+ yahoo

===========================================================================

Mosquito(es) landed!

===========================================================================

**Comment by epsylon** [comment]
Sorry. Google dorking is currently deprecated.
