### ISSUE TITLE
self.instance.success_connection is int type, using len will throw exception

### ISSUE THREAD

**Issue by buckxu** [epsylon/xsser#35]
https://github.com/epsylon/xsser/blob/9f196b7485cd79ffcd9fe4ac6e0a25420a381c5f/xsser/core/post/xml_exporter.py#L88

**Comment by epsylon** [comment]
Do you have a specific error report or is it a logical assumption knowing how it works in an abstract way?. If so, then we should change this;
(str(((len(self.instance.success_connection)
For this other:
(str(((len(int((self.instance.success_connection))
And it would work. It is right?.
