### ISSUE TITLE
XSSer.py: error: no such option: --no-head

### ISSUE THREAD

**Issue by toptuto** [epsylon/xsser#41]
When I used xsser --gtk , then I ran fly , map tab showed nothing , in cmd it said" XSSer.py: error: no such option: --no-head "
What should I suppose to do ? Thanks

**Comment by epsylon** [comment]
Hi @toptuto
Which version of XSSer are you using for your tests?
Cheers

**Comment by toptuto** [comment]
My version is XSSer v1.8[1]: "The Hive!" , I just downloaded from github

**Comment by epsylon** [comment]
Roger!. Let me check it, because some related changes were done to --no-head feature on latest update.

**Comment by epsylon** [comment]
Ok. I have found it! 
This error is happening when you click at "No-Head" GTK button at Checker(s) tab. I will commit a patch soon. 
Many thanks for your report..

**Comment by epsylon** [comment]
About Geomapping:
  1) Check that you have a folder named: **.xsser** at your **~/home/user** with geomapping databases: **GeoLiteCity.dat**
  2) If you have this warning error at shell and you want to avoid it:
_Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1_
related: https://github.com/syslog-ng/syslog-ng/issues/1446
Try to install next libraries: **libmaxminddb0**, **python-maxminddb**
ex: sudo apt-get install libmaxminddb0 python-maxminddb

**Comment by toptuto** [comment]
thanks for your support! 
But now when I reinstall the xsser, it appear the problem :
 File "/usr/local/lib/python2.7/dist-packages/xsser-1.8-py2.7.egg/core/crawler.py", line 33, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
How can I fix this , thanks

**Comment by toptuto** [comment]
I have installed bs4 already

**Comment by epsylon** [comment]
Not a good idea to continue threads with different issues. 
Btw, try to read this first:
https://stackoverflow.com/questions/5663980/importerror-no-module-named-beautifulsoup
And after that, if you still have your problem, open a new ticket with your question and share link here for future readers.
Thanks.

**Comment by epsylon** [comment]
bs4 importing error related ticket: https://github.com/epsylon/xsser/issues/42
