### ISSUE TITLE
Beautiful soup

### ISSUE THREAD

**Issue by toptuto** [epsylon/xsser#42]
I have a problem : 
Traceback (most recent call last):
  File "xsser", line 22, in <module>
    from core.main import xsser
  File "/root/xsser/core/main.py", line 38, in <module>
    from core.crawler import Crawler
  File "/root/xsser/core/crawler.py", line 33, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

I changed crawler.py from BeautifulSoup to bs4 but the problem still there , any idea ? Thanks

**Comment by epsylon** [comment]
_ImportError: No module named BeautifulSoup_

https://stackoverflow.com/questions/5663980/importerror-no-module-named-beautifulsoup

To be sure that you have bs4 correctly set at your system, check also that you have this other related libs:

- python-beautifulsoup
- python-bs4
- pypy-bs4

_sudo apt-get install python-beautifulsoup python-bs4 pypy-bs4_

Also you can try to use pip:

_pip install bs4_

**Comment by toptuto** [comment]
my have already check my system :
root@kali:~/xsser# sudo apt-get install python-bs4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-bs4 is already the newest version (4.8.0-2).

**Comment by toptuto** [comment]
ok I got it , thanks
