### ISSUE TITLE
Can't search with Bing

### ISSUE THREAD

**Issue by toptuto** [epsylon/xsser#43]
I have a list of dork. 
When I tried to search website by using dork , my cmd was : xsser -l /root/Desktop/dork.txt --De bing , but it started to search with duckduckgo , what should I do now ? Thanks

**Comment by epsylon** [comment]
You don't need to specify any path for dorks. Please, read the manual.
For dorking (with Bing):
    1) set dorks at file: _core/fuzzing/dorks.txt_
    2) run: **xsser -l --De bing**
