### ISSUE TITLE
Sucuri

### ISSUE THREAD

**Issue by toptuto** [epsylon/xsser#44]
Hello, can you bypass the Sucuri WFA ?

**Comment by epsylon** [comment]
@toptuto I think so! 
But it's not implemented as a feature on latest release. So, you need to inject "magic code" by using '--Fp' or '--payload' options. You  have some examples for bypasses here:

https://hax0rzone.blogspot.com/2015/04/sucuri-waf-xss-filter-bypass.html

**Comment by epsylon** [comment]
@toptuto A Sucuri WAF bypasser has been added to latest release: https://github.com/epsylon/xsser/commit/04a498e6a7e3cc0fea38a5d9172c7a04f136c4bc
