### ISSUE TITLE
I can't run the tool: ImportError: No module named request

### ISSUE THREAD

**Issue by F4kda7** [epsylon/xsser#59]
**Describe the bug**
i can't run the tool ( i have python2.7.17 installed and i imported the modules but when i tried to run the tool the same error appears..)

1. i installed the tool but i saw this error:
2. ┌─[user@parrot]─[~/xsser]
└──╼ $./xsser
Traceback (most recent call last):
  File "./xsser", line 22, in <module>
    from core.main import xsser
  File "/home/user/xsser/core/main.py", line 22, in <module>
    import os, re, sys, datetime, hashlib, time, urllib.request, urllib.parse, urllib.error, cgi, traceback, webbrowser, random
ImportError: No module named request

**Running environment:**
 - XSSer version 1.8.2
 - Installation method github
 - Operating system: Parrot GNU/Linux 4.8
 - Python version: i have both installed but i was using python 2.7.17 at this moment
 - kernel Linux 5.4.0-3parrot1-amd64
 - the system is udpated 

what should i do ? 

thanks

**Comment by epsylon** [comment]
Sorry @F4kda7, but since this commit: https://github.com/epsylon/xsser/commit/04a498e6a7e3cc0fea38a5d9172c7a04f136c4bc, XSSer no longer supports Python2: (https://www.python.org/doc/sunset-python-2/). 

Try to run the tool with Python3.x.y... (ex: python3 xsser)
