### ISSUE TITLE
Reverse-check is not executed for some reason 

### ISSUE THREAD

**Issue by geople** [epsylon/xsser#60]
Reverse-check steop  is not executed for some reason after finding possible xss vector, XSSER 1.8.3 version . 

**To Reproduce**
`python3 xsser --auto  -u "http://testphp.vulnweb.com/search.php?test=query" -p "searchFor=XSS&goButton=go" --reverse-check`

The script finished likes this : 

[*] Final Results:
- Injections: 1291
- Failed: 4
- Successful: 1287
- Accur: 99.69016266460109 %

[*] List of XSS injections:
-> CONGRATULATIONS: You have found: [ 1287 ] possible XSS vectors! ;-)
[Info] Aborting large screen output. Generating auto-report at: [ XSSreport.raw ] ;-)

.

**Comment by epsylon** [comment]
Probably you haven't closed correctly your previous sockets from other tests. Sometimes can happen. Take a look at your processes and kill all them (ex: gecko driver, firefox -marionette...) before to start a new one. Also, try to --delay it a bit... (ex: --delay 5)

**Comment by epsylon** [comment]
This patch should fix this "socket" issue: https://github.com/epsylon/xsser/commit/d22ef5b8f80293627dbfd1b28730e727706cb360
Thanks @geople for your report ;-)
