### ISSUE TITLE
line 3665 in print_results   in main.py if self.options.threads > 9 "str" > "int"

### ISSUE THREAD

**Issue by ezios** [epsylon/xsser#61]
in python 3.7.14
solved by  int(self.options.threads)

**Comment by shmileee** [comment]
Why did you close this issue? It hasn't been fixed in upstream.

**Comment by epsylon** [comment]
Bug reporting template: https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
