### ISSUE TITLE
Screenshots are broken in README

### ISSUE THREAD

**Issue by gingeleski** [epsylon/xsser#63]
**Describe the bug**
When viewing the README in my browser, at the project/repository's root, the embedded images are broken. They do not load.

**To Reproduce**
1. In your web browser, go to https://github.com/epsylon/xsser or https://github.com/epsylon/xsser/blob/master/README.md
2. Scroll down until you see the appropriate broken image icon for your browser.

**Expected behavior**
The screenshots should load without failure and provide helpful visuals to the human eye.

**Screenshots**
![2020-04-09 12_36_07-Window](https://user-images.githubusercontent.com/4685844/78918660-bcb95b00-7a5e-11ea-9004-c31c7382afe5.png)

**Running environment:**
N/A

**Target details:**
N/A

**Additional context**
N/A

---

**Comment by gingeleski** [comment]
The same issue also seems to affect https://github.com/epsylon/cintruder

**Comment by epsylon** [comment]
Isn't it this related with Github cache?. Btw, you can also visit it, here: https://code.03c8.net/epsylon/xsser

**Comment by epsylon** [comment]
For cintruder: https://code.03c8.net/epsylon/cintruder

**Comment by geeknik** [comment]
Using `Brave` all of the screenshots in both repositories load without issue.

**Comment by epsylon** [comment]
Or use pArAnoIA... 

https://browser.03c8.net/

Much lighter and more artisan than Brave, much more paranoid and without all the dependencies of the Chromium engine :P

https://github.com/epsylon/paranoia-browser
