### ISSUE TITLE
Valueerror when install xsser in windows 8 32bit

### ISSUE THREAD

**Issue by TeslaTuring-cmd** [epsylon/xsser#64]
When I install Xsser I got valueerror

![2020-04-17_08h59_43](https://user-images.githubusercontent.com/61399838/79529265-1e338800-8064-11ea-9023-24a29bbfb22f.png)

**Comment by epsylon** [comment]
@TeslaTuring-cmd look at the **ValueError path: "/usr/share/doc/xsser"**. This is script only works on *UNIX. You should try to install required libs manually.

**Comment by TeslaTuring-cmd** [comment]
I installed all libraries. Now how can I run the Xsser?.
Attached screenshots

**Comment by epsylon** [comment]
@TeslaTuring-cmd I don't get you... Yes. I think that if you have all required libraries, simply run it...

**Comment by TeslaTuring-cmd** [comment]
Yes I got that. It works now. Thanks for your help
