### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by qszx** [epsylon/xsser#71]
XSSer v1.8[3]: "The HiV€!" - (https://xsser.03c8.net) - 2010/2020 -> by psy

===========================================================================
Testing [Full XSS audit]... ;-)
===========================================================================

[Info] The following actions will be performed at the end:

  1- Output with detailed statistics

  2- Export results to files: 

     - a) XSSreport.raw 
     - b) XSSer_<target>_<datetime>.xml

===========================================================================

[Info] Trying method: Cross Site Tracing (XST)

--------------------------------------------------

[Error] Internal error getting -targets-

[Error] Not any valid source provided to start a test... Aborting!

===========================================================================
Traceback (most recent call last):
  File "/usr/share/xsser/xsser", line 35, in <module>
    app.run()
  File "/usr/share/xsser/core/main.py", line 3039, in run
    self.print_results()
  File "/usr/share/xsser/core/main.py", line 3229, in print_results
    fout = open("XSSreport.raw", "w") # write better than append
PermissionError: [Errno 13] Permission denied: 'XSSreport.raw'

**Comment by epsylon** [comment]
@qszx -> **PermissionError: [Errno 13] Permission denied: 'XSSreport.raw'**

You do not have sufficient permissions to create the report file. 

Try: **sudo chmod 775 -R /usr/share/xsser** -> drwxrwxr-x

BTW, You are also not entering the target in the correct way:

**[Error] Not any valid source provided to start a test.**

**Comment by epsylon** [comment]
I have made some interesting changes to control this errors:

```
[Error] Internal error getting -targets-

[Error] Not any valid source provided to start a test... Aborting!
```

At this commit: https://github.com/epsylon/xsser/commit/478242e6d8e1ca921e0ba8fa59b50106fa2f7312
