### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by qszx** [epsylon/xsser#73]
--------------------------------------------------
Total XSS Discovered: 0
--------------------------------------------------
Checker: 0 | Manual: 0 | Auto: 0 | DCP: 0 | DOM: 0 | Induced: 0 | XSR: 0 | XSA: 0 | COO: 0
--------------------------------------------------
False positives: 0 | Vulnerables: 0
-------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/share/xsser/core/gtkcontroller.py", line 1994, in run
    self.app.run(self._cmd[1:])
  File "/usr/share/xsser/core/main.py", line 3039, in run
    self.print_results()
  File "/usr/share/xsser/core/main.py", line 3764, in print_results
    if self.options.threads > 9:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by epsylon** [comment]
This error:

`TypeError: '>' not supported between instances of 'str' and 'int'`

Should be fixed after this commit:

https://github.com/epsylon/xsser/commit/478242e6d8e1ca921e0ba8fa59b50106fa2f7312

Please, try to update the tool.

------------

@qszx -> Bug report template: https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
