### ISSUE TITLE
xsser not working

### ISSUE THREAD

**Issue by Huss-wq** [epsylon/xsser#75]
When I install the xsser in my kali linux 2020.4 and run it 
this message appeared to me: 
[Error] Cannot import lib:PyCurl 

and when I install the PyCurl in kali linux and run xsser again this message appeared again how to solve this problem?. I read in some website that the solution is to change the PyCurl setup.py   and change the line 101 to read --libs instead of --static libs but I don't know how to do that so I need some help please.can anybody give me a procedure to do that please?.

**Comment by epsylon** [comment]
@Huss-wq -> "and when I install the PyCurl in kali linux"

Probably something wrong at your environment...

You can try to build your own pyCURL lib from: http://pycurl.io/docs/latest/install.html

Also you can try to install it from different sources, all of them described at **Website>Installation**:  https://xsser.03c8.net/#installation

For example:

**sudo apt-get install python3-pycurl
sudo pip3 install pycurl** 

If this doesn't work, try to detail your issue, including shell output from your commands and images, using the correct method for "Bug Reporting" tasks: https://github.com/epsylon/xsser/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
