### ISSUE TITLE
Typo in main.py - "self.repot"

### ISSUE THREAD

**Issue by deadjdona** [epsylon/xsser#79]
https://github.com/epsylon/xsser/blob/1f1b0cd790ed12ce53cc001360558a2392d7c25a/core/main.py#L2558

            self.**repot**("[Info] REPLY: Target is NOT vulnerable...\n")

should be self.report actually ^_^

**Comment by epsylon** [comment]
fixed: https://github.com/epsylon/xsser/commit/ee062fcf9431bb7429525b79a2b4fdd46396c841

Many thanks @deadjdona !
