### ISSUE TITLE
Infinity Landing gtk 

### ISSUE THREAD

**Issue by hastalamuerte** [epsylon/xsser#80]
Hello. 
Thank you for your software!  Love the mosquito style ^_^

Got troubles with Landing in gtk mode (infinite status bar run - no Fly )
Kali/debian 2022 root user

 - XSSer version [1.8.3]
 - apt install xsser
  - Python version [3.10.5]

**Comment by epsylon** [comment]
@hastalamuerte Thanks ! :-)

Are you using the version that comes with Kali Linux or have you cloned the last one from github?.

All the best.

**Comment by hastalamuerte** [comment]
> @hastalamuerte Thanks ! :-)
> 
> Are you using the version that comes with Kali Linux or have you cloned the last one from github?.
> 
> All the best.

Hello, i am using kali XSSer v1.8[4] installed by apt install . in gtk i strangly see a 1.8.3 

I am new in XSS and want to try some Xsser and Beef team. Is it possible to made some beef hook easy injecting button. For example i provide beef hook payload adress in xsser. Provide url and inject point * (or XSS) and Xsser will try to inject just provided hook ( with tampering if its not succesfull by default) . it can save time and reduce requests to url (will calm waf)
thanks . best regards! ) 
And maybe some database of injected urls wich can be refreshed to check that stored hook is still there , or reflected still is usable. 

Also there is https://github.com/shadow-workers/shadow-workers hook and some in xss-hunter panel (maybe they are deserve to be integrated too .


2. maybe its possible to add some payloads templates  (cookie steal, session steal - something most usable) to control panel too , and some info in map about succesfull fireds* of xsses. 

THX)

**Comment by epsylon** [comment]
@hastalamuerte sorry but I cannot reproduce your error on my environment/box.

 _i am using kali XSSer v1.8[4] installed by apt install_ -> https://gitlab.com/kalilinux/packages/xsser

Can you try to install it (clone) from this repository (https://github.com/epsylon/xsser/) instead of from Kali repo?

BEEF+XSSEr -> great plan! ;-)
