### ISSUE TITLE
UnboundLocalError: cannot access local variable 'payload_string' where it is not associated with a value

### ISSUE THREAD

**Issue by 23Cris** [epsylon/xsser#86]
**Describe the bug**
while using any bypasser parameter it is giving me an error

**To Reproduce**
1. Run 'xsser -u 'http://testphp.vulnweb.com/login.php/XSS' --auto --Hex
'
' xsser -u 'http://testphp.vulnweb.com/login.php/XSS' --auto --Une
'
basically any bypasser selected is giving me the unbound error.

2. See error
xsser -u 'http://testphp.vulnweb.com/login.php/XSS' --auto --Hex

![image](https://github.com/epsylon/xsser/assets/113910562/8bf45caf-7527-40a1-a5fd-1cba352c7ece)

$ xsser -u 'http://testphp.vulnweb.com/login.php/XSS' --auto --Hes :
![image](https://github.com/epsylon/xsser/assets/113910562/0b24416e-d315-425a-91b8-a62f463b0eee)

**Expected behavior**

![image](https://github.com/epsylon/xsser/assets/113910562/f83d7d46-02b8-4f4a-a91b-2094e5490afd) - not the exact process. this is a screenshot of the injection before the error
i expected it to carry out its automated xss attack using Hes parameter. I had just installed all the requirements before running the command

**Running environment:**
 - XSSer version 1.8.4
 - Installation method : preinstalleed
 - Operating system: Linux 6.1.0-kali5-amd64 x86_64
 - Python version: Python 3.11.2

**Target details:**
 - http://testphp.vulnweb.com/login.php

---

**Comment by epsylon** [comment]
cannot reproduce your bug.

![xsser-poc1](https://github.com/epsylon/xsser/assets/499387/b935de24-0509-4487-9166-b76f0a58e2d1)

**Comment by 23Cris** [comment]
It is completing without any error? I'm getting an error around 1066 execution
